### ISSUE TITLE
Verbetering [DO2 / DO4]: Build.yml

### ISSUE THREAD

**Issue by arothuis-hu** [Ishara-MacDonald/cisq1-lingo#2]
https://github.com/Ishara-MacDonald/cisq1-lingo/blob/78812bc247f458bffb34ef184dbf7841049e6336/.github/workflows/build.yml#L1-L43

1. Je build pipeline faalt nu omdat de tests geen database kunnen vinden. Daarvoor is aan het project een bijzondere configuratie toegevoegd om een vervangende in-memory database te gebruiken tijdens het testen.
Vervang ` run: mvn --batch-mode --update-snapshots verify` met het volgende, om de application in continuous integration modus te testen: 
```
run: mvn -B verify -Dspring.profiles.active=ci
```

2. Verwijder de extra stap aan het eind. Je cachet de Maven packages al eerder. Dit kan dus weg:
https://github.com/Ishara-MacDonald/cisq1-lingo/blob/78812bc247f458bffb34ef184dbf7841049e6336/.github/workflows/build.yml#L37-L42

3. Verplaats de cache sonar packages step en zet deze voor de eerdere cache maven packages stap

**Comment by Ishara-MacDonald** [comment]
Gefixt! Dankjewel voor de feedback
