### ISSUE TITLE
Verbetering [DO3]: Domeinlogica

### ISSUE THREAD

**Issue by arothuis-hu** [Ishara-MacDonald/cisq1-lingo#3]
https://github.com/Ishara-MacDonald/cisq1-lingo/blob/78812bc247f458bffb34ef184dbf7841049e6336/src/main/java/nl/hu/cisq1/lingo/trainer/domain/Feedback.java#L42-L73

De domeinlogica klopt nog niet helemaal. Waarschijnlijk worden sommige letters nu ten onrechte tweemaal als `PRESENT` aangemerkt, wanneer de betreffende letter al `CORRECT` of `PRESENT` is.

Waarschijnlijk kan je dit met 2 loopjes oplossen en een manier om bij te houden of af te strepen welke letter je al gezien hebt.

**Comment by Ishara-MacDonald** [comment]
Opgelost!
