### ISSUE TITLE
Verbetering [DO3]: Realistischere unit tests

### ISSUE THREAD

**Issue by arothuis-hu** [Ishara-MacDonald/cisq1-lingo#4]
https://github.com/Ishara-MacDonald/cisq1-lingo/blob/78812bc247f458bffb34ef184dbf7841049e6336/src/test/java/nl/hu/cisq1/lingo/trainer/domain/FeedbackTest.java#L68-L97

Probeer te werken met een parameterized test, gebaseerd op een testtabel. Je kan hiervoor de tabel gebruiken die is opgenomen in de opdrachtbeschrijving. Daar zitten al een aantal edge cases in die je nu nog niet afvangt met je test.

**Comment by Ishara-MacDonald** [comment]
FeedbackTest.java aangepast
